// <auto-generated />
using System;
using DenemeDiyetDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenemeDiyetDAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240602190736_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Diyet_Deneme_DaLL.Entities.YemekKategorileri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("YemekAdı")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("YemekKategorileris");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            YemekAdı = "Kahvaltı"
                        },
                        new
                        {
                            ID = 2,
                            YemekAdı = "Tahıl Ürünleri"
                        },
                        new
                        {
                            ID = 3,
                            YemekAdı = "Süt Ürünleri"
                        },
                        new
                        {
                            ID = 4,
                            YemekAdı = "Sebzeler"
                        },
                        new
                        {
                            ID = 5,
                            YemekAdı = "Atıştırmalık"
                        },
                        new
                        {
                            ID = 6,
                            YemekAdı = "Haşlanmış Sebzeler"
                        },
                        new
                        {
                            ID = 7,
                            YemekAdı = "Salata"
                        },
                        new
                        {
                            ID = 8,
                            YemekAdı = "Yağlar"
                        },
                        new
                        {
                            ID = 9,
                            YemekAdı = "Çorbalar"
                        });
                });

            modelBuilder.Entity("Diyet_Deneme_DaLL.Entities.YemekTarihi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Olcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamKalori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamKarbonhidrat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamProtein")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamYag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Yemek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YemekKategorileri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yiyecek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("YemekTarihis");
                });

            modelBuilder.Entity("Diyet_Deneme_DaLL.Entities.Yiyecek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adı")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.Property<double>("Karbonhidrat")
                        .HasColumnType("float");

                    b.Property<double>("Olcu")
                        .HasColumnType("float");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("Yağ")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Yiyeceks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Adı = " Peynirli Omlet",
                            Kalori = 254.0,
                            Karbonhidrat = 2.0499999999999998,
                            Olcu = 1.0,
                            Protein = 15.369999999999999,
                            Yağ = 14.9
                        },
                        new
                        {
                            ID = 2,
                            Adı = "Mantarlı Omlet",
                            Kalori = 205.0,
                            Karbonhidrat = 3.6899999999999999,
                            Olcu = 1.0,
                            Protein = 12.460000000000001,
                            Yağ = 9.9000000000000004
                        },
                        new
                        {
                            ID = 3,
                            Adı = "Menemen ",
                            Kalori = 205.0,
                            Karbonhidrat = 3.6899999999999999,
                            Olcu = 1.0,
                            Protein = 12.460000000000001,
                            Yağ = 9.9000000000000004
                        },
                        new
                        {
                            ID = 4,
                            Adı = " Kaşarlı Omlet",
                            Kalori = 260.30000000000001,
                            Karbonhidrat = 2.2000000000000002,
                            Olcu = 1.0,
                            Protein = 20.27,
                            Yağ = 13.289999999999999
                        },
                        new
                        {
                            ID = 5,
                            Adı = "Sebzeli Omlet",
                            Kalori = 205.0,
                            Karbonhidrat = 3.6899999999999999,
                            Olcu = 1.0,
                            Protein = 12.460000000000001,
                            Yağ = 9.9000000000000004
                        },
                        new
                        {
                            ID = 6,
                            Adı = "Yulaflı Omlet",
                            Kalori = 258.0,
                            Karbonhidrat = 14.4,
                            Olcu = 1.0,
                            Protein = 14.52,
                            Yağ = 10.800000000000001
                        },
                        new
                        {
                            ID = 7,
                            Adı = "Sandviç ekmeği(beyaz)",
                            Kalori = 264.0,
                            Karbonhidrat = 48.600000000000001,
                            Olcu = 1.0,
                            Protein = 8.9000000000000004,
                            Yağ = 3.2000000000000002
                        },
                        new
                        {
                            ID = 8,
                            Adı = "Sandviç ekmeği(cok tahıllı)",
                            Kalori = 312.0,
                            Karbonhidrat = 57.600000000000001,
                            Olcu = 1.0,
                            Protein = 9.5999999999999996,
                            Yağ = 2.3999999999999999
                        },
                        new
                        {
                            ID = 9,
                            Adı = "Musli",
                            Kalori = 340.0,
                            Karbonhidrat = 62.0,
                            Olcu = 1.0,
                            Protein = 10.0,
                            Yağ = 6.0
                        },
                        new
                        {
                            ID = 10,
                            Adı = "Mısır gevregi",
                            Kalori = 356.0,
                            Karbonhidrat = 84.0,
                            Olcu = 1.0,
                            Protein = 7.4000000000000004,
                            Yağ = 0.40000000000000002
                        },
                        new
                        {
                            ID = 11,
                            Adı = "Beyaz peynir",
                            Kalori = 162.0,
                            Karbonhidrat = 0.0,
                            Olcu = 1.0,
                            Protein = 14.1,
                            Yağ = 14.0
                        },
                        new
                        {
                            ID = 12,
                            Adı = "Labne peyniri",
                            Kalori = 213.5,
                            Karbonhidrat = 3.5,
                            Olcu = 1.0,
                            Protein = 6.7000000000000002,
                            Yağ = 19.300000000000001
                        },
                        new
                        {
                            ID = 13,
                            Adı = "Hellim peyniri",
                            Kalori = 320.0,
                            Karbonhidrat = 2.7999999999999998,
                            Olcu = 1.0,
                            Protein = 21.0,
                            Yağ = 25.0
                        },
                        new
                        {
                            ID = 14,
                            Adı = "Kefir",
                            Kalori = 63.0,
                            Karbonhidrat = 5.2000000000000002,
                            Olcu = 1.0,
                            Protein = 3.2999999999999998,
                            Yağ = 3.2000000000000002
                        },
                        new
                        {
                            ID = 15,
                            Adı = "Meyveli kefir",
                            Kalori = 78.0,
                            Karbonhidrat = 10.0,
                            Olcu = 1.0,
                            Protein = 2.7000000000000002,
                            Yağ = 3.0
                        },
                        new
                        {
                            ID = 16,
                            Adı = "Suzme Yogurt",
                            Kalori = 106.0,
                            Karbonhidrat = 5.0,
                            Olcu = 1.0,
                            Protein = 8.0,
                            Yağ = 6.0
                        },
                        new
                        {
                            ID = 17,
                            Adı = "Yogurt",
                            Kalori = 61.0,
                            Karbonhidrat = 4.5999999999999996,
                            Olcu = 1.0,
                            Protein = 3.4199999999999999,
                            Yağ = 3.25
                        },
                        new
                        {
                            ID = 18,
                            Adı = "Meyveli Yogurt",
                            Kalori = 93.0,
                            Karbonhidrat = 15.0,
                            Olcu = 1.0,
                            Protein = 3.1000000000000001,
                            Yağ = 2.1000000000000001
                        },
                        new
                        {
                            ID = 19,
                            Adı = "Ayran",
                            Kalori = 32.0,
                            Karbonhidrat = 2.0,
                            Olcu = 1.0,
                            Protein = 2.0,
                            Yağ = 1.8
                        },
                        new
                        {
                            ID = 20,
                            Adı = "Cacik",
                            Kalori = 41.0,
                            Karbonhidrat = 3.8999999999999999,
                            Olcu = 1.0,
                            Protein = 3.0,
                            Yağ = 0.0
                        },
                        new
                        {
                            ID = 21,
                            Adı = "Grissini",
                            Kalori = 396.0,
                            Karbonhidrat = 74.939999999999998,
                            Olcu = 1.0,
                            Protein = 10.210000000000001,
                            Yağ = 4.79
                        },
                        new
                        {
                            ID = 22,
                            Adı = "Elma",
                            Kalori = 57.0,
                            Karbonhidrat = 15.0,
                            Olcu = 1.0,
                            Protein = 0.29999999999999999,
                            Yağ = 0.20000000000000001
                        },
                        new
                        {
                            ID = 23,
                            Adı = "Armut",
                            Kalori = 60.0,
                            Karbonhidrat = 16.199999999999999,
                            Olcu = 1.0,
                            Protein = 0.40000000000000002,
                            Yağ = 0.20000000000000001
                        },
                        new
                        {
                            ID = 24,
                            Adı = "Portakal",
                            Kalori = 48.299999999999997,
                            Karbonhidrat = 12.6,
                            Olcu = 1.0,
                            Protein = 1.23,
                            Yağ = 0.10000000000000001
                        },
                        new
                        {
                            ID = 25,
                            Adı = "Greyfurt",
                            Kalori = 41.600000000000001,
                            Karbonhidrat = 10.4,
                            Olcu = 1.0,
                            Protein = 0.80000000000000004,
                            Yağ = 0.10000000000000001
                        },
                        new
                        {
                            ID = 26,
                            Adı = "Mandalina",
                            Kalori = 49.0,
                            Karbonhidrat = 12.5,
                            Olcu = 1.0,
                            Protein = 0.90000000000000002,
                            Yağ = 0.20000000000000001
                        },
                        new
                        {
                            ID = 27,
                            Adı = "Kivi",
                            Kalori = 63.0,
                            Karbonhidrat = 15.0,
                            Olcu = 1.0,
                            Protein = 1.2,
                            Yağ = 0.5
                        },
                        new
                        {
                            ID = 28,
                            Adı = "Muz",
                            Kalori = 105.0,
                            Karbonhidrat = 26.949999999999999,
                            Olcu = 1.0,
                            Protein = 1.29,
                            Yağ = 0.39000000000000001
                        },
                        new
                        {
                            ID = 29,
                            Adı = "Avokado",
                            Kalori = 160.0,
                            Karbonhidrat = 8.5299999999999994,
                            Olcu = 1.0,
                            Protein = 2.0,
                            Yağ = 14.66
                        },
                        new
                        {
                            ID = 30,
                            Adı = "Yesil Salata",
                            Kalori = 24.0,
                            Karbonhidrat = 5.0,
                            Olcu = 1.0,
                            Protein = 1.3999999999999999,
                            Yağ = 0.20000000000000001
                        },
                        new
                        {
                            ID = 31,
                            Adı = "Tavuk Salatası",
                            Kalori = 65.0,
                            Karbonhidrat = 3.23,
                            Olcu = 1.0,
                            Protein = 9.7300000000000004,
                            Yağ = 1.6499999999999999
                        },
                        new
                        {
                            ID = 32,
                            Adı = "Mercimek Corbasi",
                            Kalori = 69.0,
                            Karbonhidrat = 10.0,
                            Olcu = 1.0,
                            Protein = 4.7000000000000002,
                            Yağ = 1.3999999999999999
                        },
                        new
                        {
                            ID = 33,
                            Adı = "Tavuk Corbasi",
                            Kalori = 31.0,
                            Karbonhidrat = 3.8799999999999999,
                            Olcu = 1.0,
                            Protein = 1.6799999999999999,
                            Yağ = 1.02
                        },
                        new
                        {
                            ID = 34,
                            Adı = "Tarhana Corbasi",
                            Kalori = 82.0,
                            Karbonhidrat = 14.77,
                            Olcu = 1.0,
                            Protein = 2.4500000000000002,
                            Yağ = 1.3999999999999999
                        },
                        new
                        {
                            ID = 35,
                            Adı = "Sebze Corbasi",
                            Kalori = 43.0,
                            Karbonhidrat = 6.2599999999999998,
                            Olcu = 1.0,
                            Protein = 0.5,
                            Yağ = 1.8999999999999999
                        },
                        new
                        {
                            ID = 36,
                            Adı = "Zeytinyaglı Taze Fasulye",
                            Kalori = 81.0,
                            Karbonhidrat = 14.460000000000001,
                            Olcu = 1.0,
                            Protein = 5.4199999999999999,
                            Yağ = 0.40000000000000002
                        },
                        new
                        {
                            ID = 37,
                            Adı = "Zeytinyagli Pirasa Yemegi",
                            Kalori = 102.0,
                            Karbonhidrat = 9.8100000000000005,
                            Olcu = 1.0,
                            Protein = 2.1200000000000001,
                            Yağ = 6.4000000000000004
                        },
                        new
                        {
                            ID = 38,
                            Adı = "Havuclu Bezelye",
                            Kalori = 147.0,
                            Karbonhidrat = 11.07,
                            Olcu = 1.0,
                            Protein = 3.48,
                            Yağ = 10.380000000000001
                        },
                        new
                        {
                            ID = 39,
                            Adı = "Zeytinyagli Brokoli",
                            Kalori = 52.0,
                            Karbonhidrat = 6.6699999999999999,
                            Olcu = 1.0,
                            Protein = 2.2200000000000002,
                            Yağ = 2.48
                        },
                        new
                        {
                            ID = 40,
                            Adı = "Zeytinyagli Sebzeli Turlu",
                            Kalori = 112.0,
                            Karbonhidrat = 8.6799999999999997,
                            Olcu = 1.0,
                            Protein = 1.3300000000000001,
                            Yağ = 8.8699999999999992
                        },
                        new
                        {
                            ID = 41,
                            Adı = "Patlican Musakka",
                            Kalori = 117.0,
                            Karbonhidrat = 7.1200000000000001,
                            Olcu = 1.0,
                            Protein = 4.8200000000000003,
                            Yağ = 7.6200000000000001
                        },
                        new
                        {
                            ID = 42,
                            Adı = "Nohut Yemegi",
                            Kalori = 169.0,
                            Karbonhidrat = 15.630000000000001,
                            Olcu = 1.0,
                            Protein = 3.2200000000000002,
                            Yağ = 10.789999999999999
                        },
                        new
                        {
                            ID = 43,
                            Adı = "Bulgur pilavi",
                            Kalori = 130.0,
                            Karbonhidrat = 22.390000000000001,
                            Olcu = 1.0,
                            Protein = 3.6699999999999999,
                            Yağ = 2.6200000000000001
                        },
                        new
                        {
                            ID = 44,
                            Adı = "Pirinc pilavi",
                            Kalori = 125.0,
                            Karbonhidrat = 21.57,
                            Olcu = 1.0,
                            Protein = 2.0699999999999998,
                            Yağ = 3.2400000000000002
                        },
                        new
                        {
                            ID = 45,
                            Adı = "Makarna",
                            Kalori = 124.0,
                            Karbonhidrat = 25.120000000000001,
                            Olcu = 1.0,
                            Protein = 4.3700000000000001,
                            Yağ = 0.97999999999999998
                        },
                        new
                        {
                            ID = 46,
                            Adı = "Ekler",
                            Kalori = 174.0,
                            Karbonhidrat = 10.94,
                            Olcu = 1.0,
                            Protein = 4.2999999999999998,
                            Yağ = 12.43
                        },
                        new
                        {
                            ID = 47,
                            Adı = "Baklava",
                            Kalori = 428.0,
                            Karbonhidrat = 37.619999999999997,
                            Olcu = 1.0,
                            Protein = 6.0700000000000003,
                            Yağ = 29.030000000000001
                        },
                        new
                        {
                            ID = 48,
                            Adı = "MilkShake",
                            Kalori = 135.0,
                            Karbonhidrat = 20.109999999999999,
                            Olcu = 1.0,
                            Protein = 0.0,
                            Yağ = 4.8899999999999997
                        },
                        new
                        {
                            ID = 49,
                            Adı = "Cay",
                            Kalori = 1.0,
                            Karbonhidrat = 0.29999999999999999,
                            Olcu = 1.0,
                            Protein = 0.0,
                            Yağ = 0.0
                        },
                        new
                        {
                            ID = 50,
                            Adı = "Kola",
                            Kalori = 42.0,
                            Karbonhidrat = 10.6,
                            Olcu = 1.0,
                            Protein = 0.0,
                            Yağ = 0.0
                        });
                });

            modelBuilder.Entity("DiyetDenemeDATA.TemelOgeler.Base.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Boy")
                        .HasColumnType("float");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Kilo")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("EMail")
                        .IsUnique();

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("DiyetDenemeDATA.TemelOgeler.Base.Yemek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("YemekAdı")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Yemeks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            YemekAdı = 1
                        },
                        new
                        {
                            ID = 2,
                            YemekAdı = 2
                        },
                        new
                        {
                            ID = 3,
                            YemekAdı = 3
                        },
                        new
                        {
                            ID = 4,
                            YemekAdı = 4
                        });
                });

            modelBuilder.Entity("DiyetDenemeDATA.TemelOgeler.YiyecekYemekKategori", b =>
                {
                    b.Property<int>("YiyecekID")
                        .HasColumnType("int");

                    b.Property<int>("YemekKategorileriID")
                        .HasColumnType("int");

                    b.HasKey("YiyecekID", "YemekKategorileriID");

                    b.HasIndex("YemekKategorileriID");

                    b.ToTable("YiyecekYemekKategoris");

                    b.HasData(
                        new
                        {
                            YiyecekID = 1,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 2,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 3,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 4,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 5,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 6,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 7,
                            YemekKategorileriID = 1
                        },
                        new
                        {
                            YiyecekID = 8,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 9,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 10,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 11,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 12,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 13,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 14,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 15,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 16,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 17,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 18,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 19,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 20,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 21,
                            YemekKategorileriID = 2
                        },
                        new
                        {
                            YiyecekID = 22,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 23,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 24,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 25,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 26,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 27,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 28,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 29,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 30,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 31,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 32,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 33,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 34,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 35,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 36,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 37,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 38,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 39,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 40,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 41,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 42,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 43,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 44,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 45,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 46,
                            YemekKategorileriID = 3
                        },
                        new
                        {
                            YiyecekID = 47,
                            YemekKategorileriID = 4
                        },
                        new
                        {
                            YiyecekID = 48,
                            YemekKategorileriID = 4
                        },
                        new
                        {
                            YiyecekID = 49,
                            YemekKategorileriID = 4
                        },
                        new
                        {
                            YiyecekID = 50,
                            YemekKategorileriID = 4
                        });
                });

            modelBuilder.Entity("DiyetDenemeDATA.TemelOgeler.YiyecekYemekKategori", b =>
                {
                    b.HasOne("Diyet_Deneme_DaLL.Entities.YemekKategorileri", "YemekKategorileri")
                        .WithMany("YiyecekYemekKategoris")
                        .HasForeignKey("YemekKategorileriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diyet_Deneme_DaLL.Entities.Yiyecek", "Yiyecek")
                        .WithMany("YiyecekYemekKategoris")
                        .HasForeignKey("YiyecekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YemekKategorileri");

                    b.Navigation("Yiyecek");
                });

            modelBuilder.Entity("Diyet_Deneme_DaLL.Entities.YemekKategorileri", b =>
                {
                    b.Navigation("YiyecekYemekKategoris");
                });

            modelBuilder.Entity("Diyet_Deneme_DaLL.Entities.Yiyecek", b =>
                {
                    b.Navigation("YiyecekYemekKategoris");
                });
#pragma warning restore 612, 618
        }
    }
}
